const translations = {
    en: {
        tab_generate: 'Generate',
        tab_settings: 'Settings',
        label_prompt_presets: 'Prompt Presets',
        placeholder_select_preset: 'Select a preset...',
        btn_add: 'Add',
        btn_save: 'Save',
        btn_rename: 'Rename',
        btn_del: 'Del',
        placeholder_prompt: 'Enter your image generation prompt...',
        label_image_api: 'Image API:',
        option_image_api_banana: 'Nano Banana',
        option_image_api_gpt_image_2: 'GPT Image 2',
        label_resolution: 'Resolution:',
        placeholder_select: 'Select',
        btn_smart_ratio: 'Smart Ratio',
        checkbox_search_web: 'Search Web (Experimental)',
        checkbox_selection_mode: 'Generate by Selection Mask',
        btn_generate: 'Generate Image',
        btn_generating: 'Generating',
        btn_generating_count: 'Generating {count} image(s)',
        radio_text2img: 'Text to Image',
        radio_imgedit: 'Image Edit',
        checkbox_layer_groups: 'Use Layer Groups',
        btn_add_groups: 'Add Reference/Source Group',
        placeholder_language_select: 'Select Language',
        label_extra_settings: 'Extra Settings',
        label_language: 'Language',
        label_provider: 'Provider',
        placeholder_select_provider: 'Select Provider',
        btn_test_connection: 'Test Connection',
        label_api_key: 'API Key',
        placeholder_api_key: 'Enter API Key',
        label_base_url: 'Base URL',
        placeholder_base_url: 'https://...',
        label_banana_model_id: 'Nano Banana Model',
        placeholder_banana_model_id: 'gemini-...',
        label_gpt_image_2_model_id: 'GPT Image 2 Model',
        placeholder_gpt_image_2_model_id: 'gpt-image-2',
        label_export_settings: 'Image to Generator Export Settings',
        label_max_size: 'Max Size',
        label_quality: 'Quality',
        checkbox_debug_mode: 'Debug Mode',
        label_log_path: 'Log File Path',
        placeholder_log_path: 'Log path will appear here',
        btn_test_export: 'Test Export',
        btn_test_import: 'Test Import',
        msg_enter_preset_name: 'Enter preset name:',
        msg_rename_preset: 'Rename "{name}" to:',
        msg_delete_preset: 'Delete preset "{name}"?',
        msg_no_preset_selected: 'No preset selected',
        msg_enter_provider_name: 'Enter new provider name:',
        msg_no_provider_selected: 'No provider selected',
        msg_delete_provider: 'Delete provider "{name}"?',
        msg_testing_connection: 'Testing connection...',
        msg_provider_saved: 'Provider saved successfully',
        msg_seedream_test_success:
            '✅ Seedream Configuration Saved\n\n⚠️ Note: Seedream API cannot test connection automatically\n✓ Configuration saved, please verify API Key by generating an image\n✓ If image generation succeeds, configuration is correct',
        msg_analyzing_ratio: 'Analyzing canvas ratio...',
        msg_ratio_unchanged: '✅ Canvas is already {ratio} ratio ({width}x{height})',
        msg_ratio_adjusted:
            '✅ Canvas adjusted to {ratio} ratio\nOriginal: {oldWidth}x{oldHeight} → New: {newWidth}x{newHeight}',
        msg_adjustment_failed: '❌ Adjustment failed: {error}',
        msg_already_generating: 'Already generating...',
        msg_open_document_first: '❌ Please open a document first',
        msg_enter_prompt: 'Please enter a prompt',
        msg_configure_provider: 'Please configure a provider in Settings',
        msg_banana_model_missing: 'Please configure Nano Banana model for the selected provider',
        msg_provider_image_api_not_supported: '{provider} does not support {imageApi}',
        msg_gpt_model_missing: 'Please configure GPT Image 2 model for the selected provider',
        msg_getting_canvas_info: 'Getting canvas info...',
        msg_generating_image: 'Generating image... ({mode}, {resolution}, {ratio})',
        msg_importing_image: 'Importing image to Photoshop...',
        msg_complete: '✅ Complete! Layer: {layer}',
        msg_generation_failed: '❌ Generation failed: {error}',
        dialog_cancel: 'Cancel',
        dialog_ok: 'OK',
        dialog_placeholder_name: 'Enter name...',
    },
    zh: {
        tab_generate: '生成',
        tab_settings: '设置',
        label_prompt_presets: '提示词预设',
        placeholder_select_preset: '选择预设...',
        btn_add: '添加',
        btn_save: '保存',
        btn_rename: '重命名',
        btn_del: '删除',
        placeholder_prompt: '输入图像生成提示词...',
        label_image_api: '图片协议:',
        option_image_api_banana: 'Nano Banana',
        option_image_api_gpt_image_2: 'GPT Image 2',
        label_resolution: '分辨率:',
        placeholder_select: '选择',
        btn_smart_ratio: '智能比例',
        checkbox_search_web: '联网搜索 (实验性)',
        checkbox_selection_mode: '选区生成模式',
        btn_generate: '生成图像',
        btn_generating: '生成中...',
        btn_generating_count: '正在生成 {count} 张图像',
        radio_text2img: '文生图',
        radio_imgedit: '图像编辑',
        checkbox_layer_groups: '使用图层组',
        btn_add_groups: '添加参考/原图组',
        placeholder_language_select: '选择语言',
        label_extra_settings: '额外设置',
        label_language: '语言',
        label_provider: '服务商',
        placeholder_select_provider: '选择服务商',
        btn_test_connection: '测试连接',
        label_api_key: 'API Key',
        placeholder_api_key: '输入 API Key',
        label_base_url: 'Base URL',
        placeholder_base_url: 'https://...',
        label_banana_model_id: 'Nano Banana 模型',
        placeholder_banana_model_id: 'gemini-...',
        label_gpt_image_2_model_id: 'GPT Image 2 模型',
        placeholder_gpt_image_2_model_id: 'gpt-image-2',
        label_export_settings: '图像导出设置',
        label_max_size: '最大尺寸',
        label_quality: '质量',
        checkbox_debug_mode: '调试模式',
        label_log_path: '日志文件路径',
        placeholder_log_path: '日志路径将显示在这里',
        btn_test_export: '测试导出',
        btn_test_import: '测试导入',
        msg_enter_preset_name: '输入预设名称:',
        msg_rename_preset: '重命名 "{name}" 为:',
        msg_delete_preset: '删除预设 "{name}"?',
        msg_no_preset_selected: '未选择预设',
        msg_enter_provider_name: '输入新服务商名称:',
        msg_no_provider_selected: '未选择服务商',
        msg_delete_provider: '删除服务商 "{name}"?',
        msg_testing_connection: '正在测试连接...',
        msg_provider_saved: '服务商保存成功',
        msg_seedream_test_success:
            '✅ Seedream 配置已保存\n\n⚠️ 注意：Seedream API 无法自动测试连接\n✓ 配置已保存，请通过实际生图来验证 API Key 是否有效\n✓ 如果生图成功，说明配置正确',
        msg_analyzing_ratio: '正在分析画布比例...',
        msg_ratio_unchanged: '✅ 画布已经是 {ratio} 比例 ({width}x{height})',
        msg_ratio_adjusted:
            '✅ 画布已调整为 {ratio} 比例\n原尺寸: {oldWidth}x{oldHeight} → 新尺寸: {newWidth}x{newHeight}',
        msg_adjustment_failed: '❌ 调整失败: {error}',
        msg_already_generating: '正在生成中...',
        msg_open_document_first: '❌ 请先打开一个文档',
        msg_enter_prompt: '请输入提示词',
        msg_configure_provider: '请在设置中配置服务商',
        msg_banana_model_missing: '请先为当前服务商配置 Nano Banana 模型',
        msg_provider_image_api_not_supported: '{provider} 不支持 {imageApi}',
        msg_gpt_model_missing: '请先为当前服务商配置 GPT Image 2 模型',
        msg_getting_canvas_info: '正在获取画布信息...',
        msg_generating_image: '正在生成图像... ({mode}, {resolution}, {ratio})',
        msg_importing_image: '正在导入图像到 Photoshop...',
        msg_complete: '✅ 完成! 图层: {layer}',
        msg_generation_failed: '❌ 生成失败: {error}',
        dialog_cancel: '取消',
        dialog_ok: '确定',
        dialog_placeholder_name: '输入名称...',
    },
};

module.exports = translations;
